{
  "hash": "67cce3dfaab28fc87bbe19f44bfce496",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Predições de Resultados de Futebol\ndate: \"2022-12-20\"\nsubtitle: \"Vamos documentar uma abordagem de predição de partidas de futebol utilizando modelos de regressões de Poisson.\"\nlang: pt\nimage: richarlisson.jpg\nexecute:\n  cache: true\ncategories:\n  - R\n  - Modelos preditivos  \n---\n\n## Introdução\n\nDurante a Copa do Mundo de futebol de 2022, o interesse por predições de resultados de futebol aumentou consideravelmente. Neste sentido, este post irá demonstrar uma abordagem simples que pode gerar resultados razoáveis. O modelo utilizado neste post é baseado no trabalho [The Methodology of Red, a Football Forecasting Model from theUniversity of Reading](https://www.dropbox.com/s/184usjs7jye38lk/red-method-v1.pdf?dl=0) de J. James Reade.\n\nBasicamente, o autor utiliza um modelo de Poisson para prever as probabilidades de gols marcados por cada time. A partir dessas probabilidades, é possível estimar também a chance de vitória, empate ou derrota de cada time. Como variáveis, iremos utilizar o [Elo Rating](https://en.wikipedia.org/wiki/Elo_rating_system) de cada time e uma variável que indica se o jogo ocorreu em campo neutro ou não. O modelo a ser estimado para cada time é:\n$$ Y_{ijt}^n = \\exp\\left(\\alpha^n + \\beta_1^n R_{it} + \\beta_2^n R_{jt} + \\beta_3^n N_{ijt} \\right) \\varepsilon_{ijt}^n,~~~~ n \\in \\{time1, time2\\}, $$\nem que $Y_{ijt}^n$ representa o número de gols marcados pelo time $n$ (time 1 ou time2) em uma partida entre o time $i$ (time 1) e o time $j$ (time 2) na data $t$. As variáveis $R_{it}$ e $R_{jt}$ representam, respectivamente, os ratings dos times $i$ e $j$ antes da partida de data $t$. Por último, a variável $N_{ijt}$ é um variável *dummy* que indica se a partida foi realizada em um campo neutro. Reforçando, iremos estimar dois modelos: um para o time 1 e outro para o time 2.\n\n## Pacotes\n\nOs pacotes utilizados estão listados abaixo.\n::: {.cell hash='index_cache/html/unnamed-chunk-1_96a593ccd047849d77c2d6683ba17623'}\n\n```{.r .cell-code}\nlibrary(EloRating)\nlibrary(tidymodels)\nlibrary(tidyverse)\n\n# Tema para os gráficos\ntheme_set(theme_bw())\n```\n:::\n\n\n## Dados\n\nSerão utilizados dados de partidas entre seleções que estão disponíveis neste repositório: [martj42/international_results](https://github.com/martj42/international_results). A primeira partida disponível na base data de 30/11/1872.\n\n::: {.cell hash='index_cache/html/unnamed-chunk-2_614c0590a86ca94c8d97ef389f2729f3'}\n\n```{.r .cell-code}\ndata <- read_csv(\n  file = \"https://github.com/martj42/international_results/raw/master/results.csv\",\n  show_col_types = FALSE\n)\n\n# Remove partidas sem resultados e ajusta os nomes das variáveis de home e away\n# para team1 e team2\ndata <- data |>\n  filter(!is.na(home_score)) |>\n  rename(\n    team1 = home_team,\n    team2 = away_team,\n    team1_score = home_score,\n    team2_score = away_score\n  )\n\nhead(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  date       team1    team2    team1_score team2_score tournament city   country\n  <date>     <chr>    <chr>          <dbl>       <dbl> <chr>      <chr>  <chr>  \n1 1872-11-30 Scotland England            0           0 Friendly   Glasg… Scotla…\n2 1873-03-08 England  Scotland           4           2 Friendly   London England\n3 1874-03-07 Scotland England            2           1 Friendly   Glasg… Scotla…\n4 1875-03-06 England  Scotland           2           2 Friendly   London England\n5 1876-03-04 Scotland England            3           0 Friendly   Glasg… Scotla…\n6 1876-03-25 Scotland Wales              4           0 Friendly   Glasg… Scotla…\n# ℹ 1 more variable: neutral <lgl>\n```\n\n\n:::\n:::\n\n## Elo Rating\n\nO código abaixo irá calcular os scores (rating) do times utilizando o pacote `EloRating`. A fórmula de atualização dos scores depende um fator atualização $k$. Quanto maior esse valor, maior será o tamanho do ajuste dos scores dos times envolvidos em cada partida. Aqui, será utilizado o valor 20 igual ao adotado por J. James Reade.\n\n::: {.cell hash='index_cache/html/unnamed-chunk-3_c020c91611af45dbdb4a75d26e5724c3'}\n\n```{.r .cell-code}\n# Determina o vencendor e o perdedor\n# Em caso de empate, não importa a ordem, mas é preciso indicar que é um empate\ndata <- data |>\n  mutate(\n    winner = case_when(\n      team1_score >= team2_score ~ team1,\n      TRUE ~ team2\n    ),\n    loser = case_when(\n      team1_score < team2_score ~ team1,\n      TRUE ~ team2\n    ),\n    draw = team1_score == team2_score,\n    match_id = 1:n()\n  )\n\n# Calcula os ratings\nelo_fit <- elo.seq(\n  winner = data$winner,\n  loser = data$loser,\n  Date = data$date,\n  draw = data$draw,\n  k = 20\n)\n\n# Adiciona os ratings ao data.frame.\n# Note que utilizamos o rate do dia anterior à partida para que seja refletido\n# o score de cada time antes da partida.\ndata <- data |>\n  mutate(\n    team1_elo = extract_elo(\n      eloobject = elo_fit,\n      extractdate = pmax(min(elo_fit$truedates), date - 1),\n      IDs = team1\n    ),\n    team2_elo = extract_elo(\n      eloobject = elo_fit,\n      extractdate = pmax(min(elo_fit$truedates), date - 1),\n      IDs = team2\n    )\n  )\n```\n:::\n\n## Treino, validação e teste\n\nComo não vamos realizar nenhuma seleção de hiperparâmetros, já que o modelo é bastante simples, iremos dividir os dados apenas em dois conjuntos: treino e teste.\n\n::: {.cell hash='index_cache/html/unnamed-chunk-4_ab977ef0f4ce12e79e06f360d3ffd372'}\n\n```{.r .cell-code}\ndata <- data |>\n  mutate(friendly = tournament == \"Friendly\") |>\n  filter(date >= as.Date(\"1930-01-01\"))\n\n# Split - Treino e Teste\ntrain_test <- initial_time_split(data, prop = 0.8)\ntrain <- training(train_test)\ntest <- testing(train_test)\n```\n:::\n\n## Resultados\n\nNeste primeiro bloco de código, os modelos para os times 1 e 2 são estimados usando a função `glm()` com a opção `family = poisson`.\n\n::: {.cell hash='index_cache/html/unnamed-chunk-5_b73eb476160e8d4cda4eb5fdae24030b'}\n\n```{.r .cell-code}\nfit1 <- glm(\n  formula = team1_score ~ team1_elo + team2_elo + neutral,\n  data = train,\n  family = \"poisson\"\n)\n\nsummary(fit1)\n\npred1 <- predict(fit1, test, type = \"response\")\n\nfit2 <- glm(\n  formula = team2_score ~ team1_elo + team2_elo + neutral,\n  data = train,\n  family = \"poisson\"\n)\nsummary(fit2)\n\npred2 <- predict(fit2, test, type = \"response\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = team1_score ~ team1_elo + team2_elo + neutral, \n    family = \"poisson\", data = train)\n\nCoefficients:\n              Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  1.412e+00  4.211e-02  33.528  < 2e-16 ***\nteam1_elo    2.005e-03  3.357e-05  59.716  < 2e-16 ***\nteam2_elo   -2.876e-03  3.315e-05 -86.761  < 2e-16 ***\nneutralTRUE -7.586e-02  9.508e-03  -7.979 1.48e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 58873  on 35068  degrees of freedom\nResidual deviance: 50166  on 35065  degrees of freedom\nAIC: 119035\n\nNumber of Fisher Scoring iterations: 5\n\n\nCall:\nglm(formula = team2_score ~ team1_elo + team2_elo + neutral, \n    family = \"poisson\", data = train)\n\nCoefficients:\n              Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  5.695e-01  5.158e-02   11.04   <2e-16 ***\nteam1_elo   -2.847e-03  4.023e-05  -70.75   <2e-16 ***\nteam2_elo    2.324e-03  4.139e-05   56.14   <2e-16 ***\nneutralTRUE  2.990e-01  1.089e-02   27.45   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 53631  on 35068  degrees of freedom\nResidual deviance: 46925  on 35065  degrees of freedom\nAIC: 100215\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\nNeste segundo bloco, são computadas as probabilidades de vitória do time 1, empate e vitória do time 2. Para isso, são utilizadas as predições anteriores como o parâmetro ($\\lambda$) da distribuição de Poisson e são calculadas as probabilidades de cada time marcar 0 a 10 gols. Multiplicando as probabilidades são obtidas as probabilidades de cada placar possível. Por último, a probabilidade do time 1 ganhar é calculada como a soma das probabilidades dos placares nos quais o time 1 marca mais gols que o time2. As probabilidades de empate e vitória do time 2 são calculadas de forma similar.\n\n::: {.cell hash='index_cache/html/unnamed-chunk-6_df2188bc1ed0b2d15e88c463d3b42fad'}\n\n```{.r .cell-code}\npreds <- map_df(seq_len(nrow(test)), ~ {\n  lambda1 <- pred1[.x]\n  lambda2 <- pred2[.x]\n\n  prob1 <- dpois(0:10, lambda1)\n  prob2 <- dpois(0:10, lambda2)\n  probs <- outer(prob1, prob2)\n  probs <- probs / sum(probs)\n\n  prob_team1 <- sum(lower.tri(probs) * probs)\n  prob_team2 <- sum(upper.tri(probs) * probs)\n  prob_draw <- sum(diag(probs))\n\n  data.frame(\n    .pred_team1 = prob_team1,\n    .pred_draw = prob_draw,\n    .pred_team2 = prob_team2\n  )\n})\n```\n:::\n\nO código abaixo computa algumas métricas (log-loss e acurácia) para a base de testes.\n\n::: {.cell hash='index_cache/html/unnamed-chunk-7_ea0bd9e16bee65699923306f4deea601'}\n\n```{.r .cell-code}\n# Junta as predições aos dados de teste, cria a variável de target e a predição\n# por classe.\ntest <- test |>\n  bind_cols(preds) |>\n  mutate(\n    target = case_when(\n      team1_score > team2_score ~ \"team1\",\n      team1_score == team2_score ~ \"draw\",\n      team1_score < team2_score ~ \"team2\"\n    ),\n    target = factor(target, c(\"team1\", \"draw\", \"team2\")),\n    # predição por classe\n    pred_class = case_when(\n      .pred_team1 == pmax(.pred_team1, .pred_team2, .pred_draw) ~ \"team1\",\n      .pred_draw == pmax(.pred_team1, .pred_team2, .pred_draw) ~ \"draw\",\n      .pred_team2 == pmax(.pred_team1, .pred_team2, .pred_draw) ~ \"team2\"\n    ),\n    pred_class = factor(pred_class, c(\"team1\", \"draw\", \"team2\"))\n  )\n\nscore_acc <- accuracy(\n  data = test,\n  truth = target,\n  estimate = pred_class\n)\n\nscore_ll <- mn_log_loss(\n  data = test,\n  truth = target,\n  contains(\".pred\")\n)\n\nbind_rows(score_acc, score_ll)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  .metric     .estimator .estimate\n  <chr>       <chr>          <dbl>\n1 accuracy    multiclass     0.588\n2 mn_log_loss multiclass     0.899\n```\n\n\n:::\n:::\n\nE qual é o desempenho do modelo para as partidas da Copa do Mundo de 2022? \n\n::: {.cell hash='index_cache/html/unnamed-chunk-8_0c280a382e5bb249aae5eea03bdcac99'}\n\n```{.r .cell-code}\nscore_acc_wc2022 <- accuracy(\n  data = test |>\n    filter(date >= as.Date(\"2022-01-01\"), tournament == \"FIFA World Cup\"),\n  truth = target,\n  estimate = pred_class\n)\n\nscore_ll_wc2022 <- mn_log_loss(\n  data = test |>\n    filter(date >= as.Date(\"2022-01-01\"), tournament == \"FIFA World Cup\"),\n  truth = target,\n  contains(\".pred\")\n)\n\nbind_rows(score_acc_wc2022, score_ll_wc2022)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  .metric     .estimator .estimate\n  <chr>       <chr>          <dbl>\n1 accuracy    multiclass     0.531\n2 mn_log_loss multiclass     1.03 \n```\n\n\n:::\n:::\n\nVerifica-se uma acurácia de 53,1% e log-loss de 1.03. Estes resultados indicam uma acurácia menor do que aquela obtida para o conjunto total de teste. Por fim, para dar uma sensibilidade da qualidade dos resultados obtidos por esse modelo, deixo aqui uma comparação realizada pelo [Octosport](https://www.octosport.io/):\n\n> The FIFA world cup has just ended. It is time to share our model performance over the 64 games. We reached an accuracy of 56.2% and a log-loss of -0.982 on the final-time winner prediction (90 minutes).For comparison, famous 538 did 53.1% with a log-loss of -1.031 while kickoff.ai did 54.6% and -1.028.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}