---
layout: post
title: "Comex Vis e a visualização de dados no Brasil"
date: 2016-07-30 19:22:00 -0300
comments: true
categories: [geral]
published: true
---

No dia 28/07/2016 a Secretaria de Comércio Exterior lançou o Comex Vis, uma ferramenta de visualização interativa de dados do comércio exterior brasileiro. Nesse post faremos alguns comentários sobre o Comex Vis e sobre a visualização de dados no governo brasileiro.

<!-- More -->

## O que é visualização de dados?

Nada mais é do que representar graficamente uma informação. Em outras palavras, é pegar uma informação abstrata, seja numérica ou textual, e representá-la com padrões visuais e formas geométricas.

Não se trata de uma novidade. Na verdade, isso é algo bem antigo, desde os primórdios da matemática já desenhavam gráficos e formas para representar dados. Porém, com os avanços tecnológicos e aprimoramentos no web design, as visualizações de dados estão alcançando outro patamar: deixando de ser apenas estáticas e passando a ser interativas.

## Por que isso é importante?

De alguma forma o cérebro humano compreende melhor padrões visuais geométricos do que planilhas com diversas linhas de números ou textos. Ou seja, ao olhar um gráfico, é muito mais provável que você compreenda aspectos dos dados representados mais rapidamente do que olhando uma tabela com os mesmos dados desse gráfico.

Portanto, visualização de dados é um jeito mais simples e rápido de transmitir uma informação baseada em dados. Isso torna a visualização um artifício bastante poderoso para exploração, análise, insights e comunicação de dados, tornando os principais aspectos de um conjunto de dados algo mais rapidamente compreensivo e intuitivo.

## Visualizações interativas

O que temos notado é que as instituições mundo a fora que trabalham com divulgação de dados vem aderindo à tendência de visualização interativas de dados. 

E como anda isso no Brasil? Felizmente parece estar indo bem!

A SECEX (Secretaria de Comércio Exterior) lançou o [Comex Vis: uma ferramenta de visualização interativa de dados do comércio exterior brasileiro](http://www.mdic.gov.br/comercio-exterior/estatisticas-de-comercio-exterior/comex-vis). 

O objetivo do projeto é disponibilizar visualizações interativas dos dados de importação e exportação brasileira, cobrindo diversos aspectos e variáveis: parceiros comerciais, continentes, blocos, produtos e classificações, unidade da federação, etc...

O projeto foi completamente desenvolvido com plataformas open source, com o R e o [D3Plus](http://d3plus.org/), que é um pacote javscript (baseado em [D3](https://d3js.org/)) capaz de criar visualizações interativas concisas, simples e bonitas.

O Comex Vis segue a mesma linha de outros portais que também utilizam o D3Plus, como por exemplo o [The Observatory of Economic Complexity](http://atlas.media.mit.edu/en/), o [Data USA](http://datausa.io/) e o excelente [Data VIVA](http://www.dataviva.info/pt/). Vale muito a pena conhecer todos eles.

Sobre visualização de dados de comércio exterior, o Comtrade, da ONU, tem um portal com diversas divulgações interativas: o [Comtrade Labs](http://comtrade.un.org/labs/)

Na mesma linha de divulgação de visualizações interativas, o [BNDES também tem uma página com diversos gráficos: o BNDES Transparente](http://www.bndes.gov.br/SiteBNDES/bndes/bndes_pt/Institucional/BNDES_Transparente/). Os gráficos foram construidos em [Tableau](http://www.tableau.com/pt-br), uma poderosa ferramenta de BI, porém, não é gratuito.

Outros!?!?

## Mais sobre visualização de dados

Se você está interessado em aprender mais sobre visualizações, assim como nós, recomendamos alguns sites que podem ajudar nessa jornada:

[DataViz Catalogue](http://www.datavizcatalogue.com/) - Um excelente catálogo explicativo sobre diversos tipos de visualizações, incluindo como e quando usá-las, seus pontos fortes e pontos fracos.

[O`Reilly - Effective Data Visualization](https://player.oreilly.com/videos/9781491917015) - Uma sequência de videos explorando diversos aspectos sobre visualização de dados. Infelizmente nem todos os videos são gratuitos, mas os gratuitos já são excelentes.

Outros!?!?